--- #YAML:1.0
name: wikimedia-graph
abstract: Integrate Graph::Easy into Wikimedia
version: 0.15
version_from: graphcnv
license: gpl
distribution_type: module
generated_by: wikimedia-graph version 0.15
installdirs: site
requires:
  Digest::SHA1: 2.1
  Graph::Easy: 0.34
