--- #YAML:1.0
name: wikimedia-graph
abstract: Integrate Graph::Easy into Wikimedia
version: 0.12
version_from: graphcnv
license: gpl
distribution_type: module
generated_by: wikimedia-graph version 0.12
installdirs: site
requires:
  Graph::Easy: 0.3
