--- #YAML:1.0
name: wikimedia-graph
abstract: Integrate Graph::Easy into Wikimedia
version: 0.14
version_from: graphcnv
license: gpl
distribution_type: module
generated_by: wikimedia-graph version 0.14
installdirs: site
requires:
  Graph::Easy: 0.32
